// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: telemetry.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gear int32

const (
	Gear_GEAR_UNSPECIFIED Gear = 0
	Gear_GEAR_PARK        Gear = 1
	Gear_GEAR_REVERSE     Gear = 2
	Gear_GEAR_NEUTRAL     Gear = 3
	Gear_GEAR_DRIVE       Gear = 4
)

// Enum value maps for Gear.
var (
	Gear_name = map[int32]string{
		0: "GEAR_UNSPECIFIED",
		1: "GEAR_PARK",
		2: "GEAR_REVERSE",
		3: "GEAR_NEUTRAL",
		4: "GEAR_DRIVE",
	}
	Gear_value = map[string]int32{
		"GEAR_UNSPECIFIED": 0,
		"GEAR_PARK":        1,
		"GEAR_REVERSE":     2,
		"GEAR_NEUTRAL":     3,
		"GEAR_DRIVE":       4,
	}
)

func (x Gear) Enum() *Gear {
	p := new(Gear)
	*p = x
	return p
}

func (x Gear) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gear) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[0].Descriptor()
}

func (Gear) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[0]
}

func (x Gear) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gear.Descriptor instead.
func (Gear) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

type VehicleModel int32

const (
	VehicleModel_VEHICLE_MODEL_UNSPECIFIED VehicleModel = 0
	// Tesla Models
	VehicleModel_VEHICLE_MODEL_TESLA_MODEL_3    VehicleModel = 1
	VehicleModel_VEHICLE_MODEL_TESLA_MODEL_Y    VehicleModel = 2
	VehicleModel_VEHICLE_MODEL_TESLA_MODEL_S    VehicleModel = 3
	VehicleModel_VEHICLE_MODEL_TESLA_MODEL_X    VehicleModel = 4
	VehicleModel_VEHICLE_MODEL_TESLA_CYBERTRUCK VehicleModel = 5
	VehicleModel_VEHICLE_MODEL_TESLA_SEMI       VehicleModel = 6
	// Rivian Models
	VehicleModel_VEHICLE_MODEL_RIVIAN_R1T VehicleModel = 7
	VehicleModel_VEHICLE_MODEL_RIVIAN_R1S VehicleModel = 8
	VehicleModel_VEHICLE_MODEL_RIVIAN_EDV VehicleModel = 9 // Electric Delivery Van (Amazon Fleet)
)

// Enum value maps for VehicleModel.
var (
	VehicleModel_name = map[int32]string{
		0: "VEHICLE_MODEL_UNSPECIFIED",
		1: "VEHICLE_MODEL_TESLA_MODEL_3",
		2: "VEHICLE_MODEL_TESLA_MODEL_Y",
		3: "VEHICLE_MODEL_TESLA_MODEL_S",
		4: "VEHICLE_MODEL_TESLA_MODEL_X",
		5: "VEHICLE_MODEL_TESLA_CYBERTRUCK",
		6: "VEHICLE_MODEL_TESLA_SEMI",
		7: "VEHICLE_MODEL_RIVIAN_R1T",
		8: "VEHICLE_MODEL_RIVIAN_R1S",
		9: "VEHICLE_MODEL_RIVIAN_EDV",
	}
	VehicleModel_value = map[string]int32{
		"VEHICLE_MODEL_UNSPECIFIED":      0,
		"VEHICLE_MODEL_TESLA_MODEL_3":    1,
		"VEHICLE_MODEL_TESLA_MODEL_Y":    2,
		"VEHICLE_MODEL_TESLA_MODEL_S":    3,
		"VEHICLE_MODEL_TESLA_MODEL_X":    4,
		"VEHICLE_MODEL_TESLA_CYBERTRUCK": 5,
		"VEHICLE_MODEL_TESLA_SEMI":       6,
		"VEHICLE_MODEL_RIVIAN_R1T":       7,
		"VEHICLE_MODEL_RIVIAN_R1S":       8,
		"VEHICLE_MODEL_RIVIAN_EDV":       9,
	}
)

func (x VehicleModel) Enum() *VehicleModel {
	p := new(VehicleModel)
	*p = x
	return p
}

func (x VehicleModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleModel) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[1].Descriptor()
}

func (VehicleModel) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[1]
}

func (x VehicleModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleModel.Descriptor instead.
func (VehicleModel) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

type BatteryState_BatteryStatus int32

const (
	BatteryState_BATTERY_STATUS_UNSPECIFIED BatteryState_BatteryStatus = 0
	BatteryState_BATTERY_STATUS_OK          BatteryState_BatteryStatus = 1
	BatteryState_BATTERY_STATUS_CHARGING    BatteryState_BatteryStatus = 2
	BatteryState_BATTERY_STATUS_DISCHARGING BatteryState_BatteryStatus = 3
	BatteryState_BATTERY_STATUS_FAULT       BatteryState_BatteryStatus = 4
)

// Enum value maps for BatteryState_BatteryStatus.
var (
	BatteryState_BatteryStatus_name = map[int32]string{
		0: "BATTERY_STATUS_UNSPECIFIED",
		1: "BATTERY_STATUS_OK",
		2: "BATTERY_STATUS_CHARGING",
		3: "BATTERY_STATUS_DISCHARGING",
		4: "BATTERY_STATUS_FAULT",
	}
	BatteryState_BatteryStatus_value = map[string]int32{
		"BATTERY_STATUS_UNSPECIFIED": 0,
		"BATTERY_STATUS_OK":          1,
		"BATTERY_STATUS_CHARGING":    2,
		"BATTERY_STATUS_DISCHARGING": 3,
		"BATTERY_STATUS_FAULT":       4,
	}
)

func (x BatteryState_BatteryStatus) Enum() *BatteryState_BatteryStatus {
	p := new(BatteryState_BatteryStatus)
	*p = x
	return p
}

func (x BatteryState_BatteryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatteryState_BatteryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[2].Descriptor()
}

func (BatteryState_BatteryStatus) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[2]
}

func (x BatteryState_BatteryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatteryState_BatteryStatus.Descriptor instead.
func (BatteryState_BatteryStatus) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

type ChargingState_ChargeState int32

const (
	ChargingState_CHARGE_STATE_UNSPECIFIED  ChargingState_ChargeState = 0
	ChargingState_CHARGE_STATE_DISCONNECTED ChargingState_ChargeState = 1
	ChargingState_CHARGE_STATE_CONNECTED    ChargingState_ChargeState = 2
	ChargingState_CHARGE_STATE_CHARGING     ChargingState_ChargeState = 3
	ChargingState_CHARGE_STATE_COMPLETE     ChargingState_ChargeState = 4
	ChargingState_CHARGE_STATE_STOPPED      ChargingState_ChargeState = 5
	ChargingState_CHARGE_STATE_FAULT        ChargingState_ChargeState = 6
)

// Enum value maps for ChargingState_ChargeState.
var (
	ChargingState_ChargeState_name = map[int32]string{
		0: "CHARGE_STATE_UNSPECIFIED",
		1: "CHARGE_STATE_DISCONNECTED",
		2: "CHARGE_STATE_CONNECTED",
		3: "CHARGE_STATE_CHARGING",
		4: "CHARGE_STATE_COMPLETE",
		5: "CHARGE_STATE_STOPPED",
		6: "CHARGE_STATE_FAULT",
	}
	ChargingState_ChargeState_value = map[string]int32{
		"CHARGE_STATE_UNSPECIFIED":  0,
		"CHARGE_STATE_DISCONNECTED": 1,
		"CHARGE_STATE_CONNECTED":    2,
		"CHARGE_STATE_CHARGING":     3,
		"CHARGE_STATE_COMPLETE":     4,
		"CHARGE_STATE_STOPPED":      5,
		"CHARGE_STATE_FAULT":        6,
	}
)

func (x ChargingState_ChargeState) Enum() *ChargingState_ChargeState {
	p := new(ChargingState_ChargeState)
	*p = x
	return p
}

func (x ChargingState_ChargeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargingState_ChargeState) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[3].Descriptor()
}

func (ChargingState_ChargeState) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[3]
}

func (x ChargingState_ChargeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargingState_ChargeState.Descriptor instead.
func (ChargingState_ChargeState) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2, 0}
}

type ChargingState_ChargerType int32

const (
	ChargingState_CHARGER_TYPE_UNSPECIFIED ChargingState_ChargerType = 0
	ChargingState_CHARGER_TYPE_AC_LEVEL_1  ChargingState_ChargerType = 1
	ChargingState_CHARGER_TYPE_AC_LEVEL_2  ChargingState_ChargerType = 2
	ChargingState_CHARGER_TYPE_DC_FAST     ChargingState_ChargerType = 3
)

// Enum value maps for ChargingState_ChargerType.
var (
	ChargingState_ChargerType_name = map[int32]string{
		0: "CHARGER_TYPE_UNSPECIFIED",
		1: "CHARGER_TYPE_AC_LEVEL_1",
		2: "CHARGER_TYPE_AC_LEVEL_2",
		3: "CHARGER_TYPE_DC_FAST",
	}
	ChargingState_ChargerType_value = map[string]int32{
		"CHARGER_TYPE_UNSPECIFIED": 0,
		"CHARGER_TYPE_AC_LEVEL_1":  1,
		"CHARGER_TYPE_AC_LEVEL_2":  2,
		"CHARGER_TYPE_DC_FAST":     3,
	}
)

func (x ChargingState_ChargerType) Enum() *ChargingState_ChargerType {
	p := new(ChargingState_ChargerType)
	*p = x
	return p
}

func (x ChargingState_ChargerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargingState_ChargerType) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[4].Descriptor()
}

func (ChargingState_ChargerType) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[4]
}

func (x ChargingState_ChargerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargingState_ChargerType.Descriptor instead.
func (ChargingState_ChargerType) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2, 1}
}

type MotorState_MotorPosition int32

const (
	MotorState_MOTOR_POSITION_UNSPECIFIED MotorState_MotorPosition = 0
	// Single / Axle-based dual motor setups (Tesla Model 3/Y, Ford, etc.)
	MotorState_MOTOR_POSITION_FRONT MotorState_MotorPosition = 1
	MotorState_MOTOR_POSITION_REAR  MotorState_MotorPosition = 2
	// Independent wheel quad-motor setups (Rivian R1T Quad, Cybertruck Cyberbeast, etc.)
	MotorState_MOTOR_POSITION_FRONT_LEFT  MotorState_MotorPosition = 3
	MotorState_MOTOR_POSITION_FRONT_RIGHT MotorState_MotorPosition = 4
	MotorState_MOTOR_POSITION_REAR_LEFT   MotorState_MotorPosition = 5
	MotorState_MOTOR_POSITION_REAR_RIGHT  MotorState_MotorPosition = 6
)

// Enum value maps for MotorState_MotorPosition.
var (
	MotorState_MotorPosition_name = map[int32]string{
		0: "MOTOR_POSITION_UNSPECIFIED",
		1: "MOTOR_POSITION_FRONT",
		2: "MOTOR_POSITION_REAR",
		3: "MOTOR_POSITION_FRONT_LEFT",
		4: "MOTOR_POSITION_FRONT_RIGHT",
		5: "MOTOR_POSITION_REAR_LEFT",
		6: "MOTOR_POSITION_REAR_RIGHT",
	}
	MotorState_MotorPosition_value = map[string]int32{
		"MOTOR_POSITION_UNSPECIFIED": 0,
		"MOTOR_POSITION_FRONT":       1,
		"MOTOR_POSITION_REAR":        2,
		"MOTOR_POSITION_FRONT_LEFT":  3,
		"MOTOR_POSITION_FRONT_RIGHT": 4,
		"MOTOR_POSITION_REAR_LEFT":   5,
		"MOTOR_POSITION_REAR_RIGHT":  6,
	}
)

func (x MotorState_MotorPosition) Enum() *MotorState_MotorPosition {
	p := new(MotorState_MotorPosition)
	*p = x
	return p
}

func (x MotorState_MotorPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorState_MotorPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[5].Descriptor()
}

func (MotorState_MotorPosition) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[5]
}

func (x MotorState_MotorPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorState_MotorPosition.Descriptor instead.
func (MotorState_MotorPosition) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3, 0}
}

type MotorState_MotorStatus int32

const (
	MotorState_MOTOR_STATUS_UNSPECIFIED     MotorState_MotorStatus = 0
	MotorState_MOTOR_STATUS_READY_TO_DRIVE  MotorState_MotorStatus = 1
	MotorState_MOTOR_STATUS_READY_TO_CHARGE MotorState_MotorStatus = 2
	MotorState_MOTOR_STATUS_FAULT           MotorState_MotorStatus = 3
)

// Enum value maps for MotorState_MotorStatus.
var (
	MotorState_MotorStatus_name = map[int32]string{
		0: "MOTOR_STATUS_UNSPECIFIED",
		1: "MOTOR_STATUS_READY_TO_DRIVE",
		2: "MOTOR_STATUS_READY_TO_CHARGE",
		3: "MOTOR_STATUS_FAULT",
	}
	MotorState_MotorStatus_value = map[string]int32{
		"MOTOR_STATUS_UNSPECIFIED":     0,
		"MOTOR_STATUS_READY_TO_DRIVE":  1,
		"MOTOR_STATUS_READY_TO_CHARGE": 2,
		"MOTOR_STATUS_FAULT":           3,
	}
)

func (x MotorState_MotorStatus) Enum() *MotorState_MotorStatus {
	p := new(MotorState_MotorStatus)
	*p = x
	return p
}

func (x MotorState_MotorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorState_MotorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[6].Descriptor()
}

func (MotorState_MotorStatus) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[6]
}

func (x MotorState_MotorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorState_MotorStatus.Descriptor instead.
func (MotorState_MotorStatus) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3, 1}
}

type SuspensionState_RideHeight int32

const (
	SuspensionState_RIDE_HEIGHT_UNSPECIFIED SuspensionState_RideHeight = 0
	SuspensionState_RIDE_HEIGHT_VERY_LOW    SuspensionState_RideHeight = 1
	SuspensionState_RIDE_HEIGHT_LOW         SuspensionState_RideHeight = 2
	SuspensionState_RIDE_HEIGHT_STANDARD    SuspensionState_RideHeight = 3
	SuspensionState_RIDE_HEIGHT_HIGH        SuspensionState_RideHeight = 4
	SuspensionState_RIDE_HEIGHT_VERY_HIGH   SuspensionState_RideHeight = 5
)

// Enum value maps for SuspensionState_RideHeight.
var (
	SuspensionState_RideHeight_name = map[int32]string{
		0: "RIDE_HEIGHT_UNSPECIFIED",
		1: "RIDE_HEIGHT_VERY_LOW",
		2: "RIDE_HEIGHT_LOW",
		3: "RIDE_HEIGHT_STANDARD",
		4: "RIDE_HEIGHT_HIGH",
		5: "RIDE_HEIGHT_VERY_HIGH",
	}
	SuspensionState_RideHeight_value = map[string]int32{
		"RIDE_HEIGHT_UNSPECIFIED": 0,
		"RIDE_HEIGHT_VERY_LOW":    1,
		"RIDE_HEIGHT_LOW":         2,
		"RIDE_HEIGHT_STANDARD":    3,
		"RIDE_HEIGHT_HIGH":        4,
		"RIDE_HEIGHT_VERY_HIGH":   5,
	}
)

func (x SuspensionState_RideHeight) Enum() *SuspensionState_RideHeight {
	p := new(SuspensionState_RideHeight)
	*p = x
	return p
}

func (x SuspensionState_RideHeight) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuspensionState_RideHeight) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[7].Descriptor()
}

func (SuspensionState_RideHeight) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[7]
}

func (x SuspensionState_RideHeight) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuspensionState_RideHeight.Descriptor instead.
func (SuspensionState_RideHeight) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6, 0}
}

type VehicleAlert_AlertLevel int32

const (
	VehicleAlert_ALERT_LEVEL_UNSPECIFIED VehicleAlert_AlertLevel = 0
	VehicleAlert_ALERT_LEVEL_INFO        VehicleAlert_AlertLevel = 1
	VehicleAlert_ALERT_LEVEL_WARNING     VehicleAlert_AlertLevel = 2
	VehicleAlert_ALERT_LEVEL_ERROR       VehicleAlert_AlertLevel = 3
	VehicleAlert_ALERT_LEVEL_CRITICAL    VehicleAlert_AlertLevel = 4
)

// Enum value maps for VehicleAlert_AlertLevel.
var (
	VehicleAlert_AlertLevel_name = map[int32]string{
		0: "ALERT_LEVEL_UNSPECIFIED",
		1: "ALERT_LEVEL_INFO",
		2: "ALERT_LEVEL_WARNING",
		3: "ALERT_LEVEL_ERROR",
		4: "ALERT_LEVEL_CRITICAL",
	}
	VehicleAlert_AlertLevel_value = map[string]int32{
		"ALERT_LEVEL_UNSPECIFIED": 0,
		"ALERT_LEVEL_INFO":        1,
		"ALERT_LEVEL_WARNING":     2,
		"ALERT_LEVEL_ERROR":       3,
		"ALERT_LEVEL_CRITICAL":    4,
	}
)

func (x VehicleAlert_AlertLevel) Enum() *VehicleAlert_AlertLevel {
	p := new(VehicleAlert_AlertLevel)
	*p = x
	return p
}

func (x VehicleAlert_AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleAlert_AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[8].Descriptor()
}

func (VehicleAlert_AlertLevel) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[8]
}

func (x VehicleAlert_AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleAlert_AlertLevel.Descriptor instead.
func (VehicleAlert_AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{9, 0}
}

type GPSLocation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Latitude         float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude         float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Speed            float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading          float64                `protobuf:"fixed64,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Pdop             float64                `protobuf:"fixed64,6,opt,name=pdop,proto3" json:"pdop,omitempty"`
	Hdop             float64                `protobuf:"fixed64,7,opt,name=hdop,proto3" json:"hdop,omitempty"`
	LocationProvider string                 `protobuf:"bytes,8,opt,name=location_provider,json=locationProvider,proto3" json:"location_provider,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GPSLocation) Reset() {
	*x = GPSLocation{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSLocation) ProtoMessage() {}

func (x *GPSLocation) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSLocation.ProtoReflect.Descriptor instead.
func (*GPSLocation) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *GPSLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSLocation) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *GPSLocation) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GPSLocation) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *GPSLocation) GetPdop() float64 {
	if x != nil {
		return x.Pdop
	}
	return 0
}

func (x *GPSLocation) GetHdop() float64 {
	if x != nil {
		return x.Hdop
	}
	return 0
}

func (x *GPSLocation) GetLocationProvider() string {
	if x != nil {
		return x.LocationProvider
	}
	return ""
}

type BatteryState struct {
	state                  protoimpl.MessageState     `protogen:"open.v1"`
	CellVoltage            []float32                  `protobuf:"fixed32,1,rep,packed,name=cell_voltage,json=cellVoltage,proto3" json:"cell_voltage,omitempty"`
	StateOfCharge          float32                    `protobuf:"fixed32,2,opt,name=state_of_charge,json=stateOfCharge,proto3" json:"state_of_charge,omitempty"`
	PackVoltage            float32                    `protobuf:"fixed32,3,opt,name=pack_voltage,json=packVoltage,proto3" json:"pack_voltage,omitempty"`
	PackCurrent            float32                    `protobuf:"fixed32,4,opt,name=pack_current,json=packCurrent,proto3" json:"pack_current,omitempty"`
	MaxCellTemperature     float32                    `protobuf:"fixed32,5,opt,name=max_cell_temperature,json=maxCellTemperature,proto3" json:"max_cell_temperature,omitempty"`
	MinCellTemperature     float32                    `protobuf:"fixed32,6,opt,name=min_cell_temperature,json=minCellTemperature,proto3" json:"min_cell_temperature,omitempty"`
	PackTemperature        float32                    `protobuf:"fixed32,7,opt,name=pack_temperature,json=packTemperature,proto3" json:"pack_temperature,omitempty"`
	PackPower              float32                    `protobuf:"fixed32,8,opt,name=pack_power,json=packPower,proto3" json:"pack_power,omitempty"`
	PackHealth             float32                    `protobuf:"fixed32,9,opt,name=pack_health,json=packHealth,proto3" json:"pack_health,omitempty"`
	PackRemainingCapacity  float32                    `protobuf:"fixed32,10,opt,name=pack_remaining_capacity,json=packRemainingCapacity,proto3" json:"pack_remaining_capacity,omitempty"`
	PackCycleCount         int32                      `protobuf:"varint,11,opt,name=pack_cycle_count,json=packCycleCount,proto3" json:"pack_cycle_count,omitempty"`
	PackStatus             BatteryState_BatteryStatus `protobuf:"varint,12,opt,name=pack_status,json=packStatus,proto3,enum=fleet.telemetry.v1.BatteryState_BatteryStatus" json:"pack_status,omitempty"`
	MinCellVoltage         float32                    `protobuf:"fixed32,13,opt,name=min_cell_voltage,json=minCellVoltage,proto3" json:"min_cell_voltage,omitempty"`
	MaxCellVoltage         float32                    `protobuf:"fixed32,14,opt,name=max_cell_voltage,json=maxCellVoltage,proto3" json:"max_cell_voltage,omitempty"`
	LowVoltageBatteryVolts float32                    `protobuf:"fixed32,15,opt,name=low_voltage_battery_volts,json=lowVoltageBatteryVolts,proto3" json:"low_voltage_battery_volts,omitempty"` // 12V / 16V auxiliary battery
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatteryState) Reset() {
	*x = BatteryState{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryState) ProtoMessage() {}

func (x *BatteryState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryState.ProtoReflect.Descriptor instead.
func (*BatteryState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryState) GetCellVoltage() []float32 {
	if x != nil {
		return x.CellVoltage
	}
	return nil
}

func (x *BatteryState) GetStateOfCharge() float32 {
	if x != nil {
		return x.StateOfCharge
	}
	return 0
}

func (x *BatteryState) GetPackVoltage() float32 {
	if x != nil {
		return x.PackVoltage
	}
	return 0
}

func (x *BatteryState) GetPackCurrent() float32 {
	if x != nil {
		return x.PackCurrent
	}
	return 0
}

func (x *BatteryState) GetMaxCellTemperature() float32 {
	if x != nil {
		return x.MaxCellTemperature
	}
	return 0
}

func (x *BatteryState) GetMinCellTemperature() float32 {
	if x != nil {
		return x.MinCellTemperature
	}
	return 0
}

func (x *BatteryState) GetPackTemperature() float32 {
	if x != nil {
		return x.PackTemperature
	}
	return 0
}

func (x *BatteryState) GetPackPower() float32 {
	if x != nil {
		return x.PackPower
	}
	return 0
}

func (x *BatteryState) GetPackHealth() float32 {
	if x != nil {
		return x.PackHealth
	}
	return 0
}

func (x *BatteryState) GetPackRemainingCapacity() float32 {
	if x != nil {
		return x.PackRemainingCapacity
	}
	return 0
}

func (x *BatteryState) GetPackCycleCount() int32 {
	if x != nil {
		return x.PackCycleCount
	}
	return 0
}

func (x *BatteryState) GetPackStatus() BatteryState_BatteryStatus {
	if x != nil {
		return x.PackStatus
	}
	return BatteryState_BATTERY_STATUS_UNSPECIFIED
}

func (x *BatteryState) GetMinCellVoltage() float32 {
	if x != nil {
		return x.MinCellVoltage
	}
	return 0
}

func (x *BatteryState) GetMaxCellVoltage() float32 {
	if x != nil {
		return x.MaxCellVoltage
	}
	return 0
}

func (x *BatteryState) GetLowVoltageBatteryVolts() float32 {
	if x != nil {
		return x.LowVoltageBatteryVolts
	}
	return 0
}

type ChargingState struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	State                  ChargingState_ChargeState `protobuf:"varint,1,opt,name=state,proto3,enum=fleet.telemetry.v1.ChargingState_ChargeState" json:"state,omitempty"`
	ChargerType            ChargingState_ChargerType `protobuf:"varint,2,opt,name=charger_type,json=chargerType,proto3,enum=fleet.telemetry.v1.ChargingState_ChargerType" json:"charger_type,omitempty"`
	ChargePortDoorOpen     bool                      `protobuf:"varint,3,opt,name=charge_port_door_open,json=chargePortDoorOpen,proto3" json:"charge_port_door_open,omitempty"`
	ChargePortLatchEngaged bool                      `protobuf:"varint,4,opt,name=charge_port_latch_engaged,json=chargePortLatchEngaged,proto3" json:"charge_port_latch_engaged,omitempty"`
	// Electrical metrics
	ChargerVoltage       float32 `protobuf:"fixed32,5,opt,name=charger_voltage,json=chargerVoltage,proto3" json:"charger_voltage,omitempty"`                     // Volts (AC RMS or DC)
	ChargerActualCurrent float32 `protobuf:"fixed32,6,opt,name=charger_actual_current,json=chargerActualCurrent,proto3" json:"charger_actual_current,omitempty"` // Amperes
	ChargerPilotCurrent  float32 `protobuf:"fixed32,7,opt,name=charger_pilot_current,json=chargerPilotCurrent,proto3" json:"charger_pilot_current,omitempty"`    // Max available current offered by EVSE
	ChargerPhases        int32   `protobuf:"varint,8,opt,name=charger_phases,json=chargerPhases,proto3" json:"charger_phases,omitempty"`                         // 1 or 3 phase AC
	ChargingPowerKw      float32 `protobuf:"fixed32,9,opt,name=charging_power_kw,json=chargingPowerKw,proto3" json:"charging_power_kw,omitempty"`                // Instantaneous kW
	// Session & Progress metrics
	SessionEnergyAddedKwh  float32 `protobuf:"fixed32,10,opt,name=session_energy_added_kwh,json=sessionEnergyAddedKwh,proto3" json:"session_energy_added_kwh,omitempty"`
	ChargeRateKmPerHour    float32 `protobuf:"fixed32,11,opt,name=charge_rate_km_per_hour,json=chargeRateKmPerHour,proto3" json:"charge_rate_km_per_hour,omitempty"`
	MinutesToFullCharge    int32   `protobuf:"varint,12,opt,name=minutes_to_full_charge,json=minutesToFullCharge,proto3" json:"minutes_to_full_charge,omitempty"`
	ChargeLimitSocPct      int32   `protobuf:"varint,13,opt,name=charge_limit_soc_pct,json=chargeLimitSocPct,proto3" json:"charge_limit_soc_pct,omitempty"`            // Target SoC limit (e.g. 80%)
	BatteryPreconditioning bool    `protobuf:"varint,14,opt,name=battery_preconditioning,json=batteryPreconditioning,proto3" json:"battery_preconditioning,omitempty"` // Battery heating for fast charging
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChargingState) Reset() {
	*x = ChargingState{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargingState) ProtoMessage() {}

func (x *ChargingState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargingState.ProtoReflect.Descriptor instead.
func (*ChargingState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ChargingState) GetState() ChargingState_ChargeState {
	if x != nil {
		return x.State
	}
	return ChargingState_CHARGE_STATE_UNSPECIFIED
}

func (x *ChargingState) GetChargerType() ChargingState_ChargerType {
	if x != nil {
		return x.ChargerType
	}
	return ChargingState_CHARGER_TYPE_UNSPECIFIED
}

func (x *ChargingState) GetChargePortDoorOpen() bool {
	if x != nil {
		return x.ChargePortDoorOpen
	}
	return false
}

func (x *ChargingState) GetChargePortLatchEngaged() bool {
	if x != nil {
		return x.ChargePortLatchEngaged
	}
	return false
}

func (x *ChargingState) GetChargerVoltage() float32 {
	if x != nil {
		return x.ChargerVoltage
	}
	return 0
}

func (x *ChargingState) GetChargerActualCurrent() float32 {
	if x != nil {
		return x.ChargerActualCurrent
	}
	return 0
}

func (x *ChargingState) GetChargerPilotCurrent() float32 {
	if x != nil {
		return x.ChargerPilotCurrent
	}
	return 0
}

func (x *ChargingState) GetChargerPhases() int32 {
	if x != nil {
		return x.ChargerPhases
	}
	return 0
}

func (x *ChargingState) GetChargingPowerKw() float32 {
	if x != nil {
		return x.ChargingPowerKw
	}
	return 0
}

func (x *ChargingState) GetSessionEnergyAddedKwh() float32 {
	if x != nil {
		return x.SessionEnergyAddedKwh
	}
	return 0
}

func (x *ChargingState) GetChargeRateKmPerHour() float32 {
	if x != nil {
		return x.ChargeRateKmPerHour
	}
	return 0
}

func (x *ChargingState) GetMinutesToFullCharge() int32 {
	if x != nil {
		return x.MinutesToFullCharge
	}
	return 0
}

func (x *ChargingState) GetChargeLimitSocPct() int32 {
	if x != nil {
		return x.ChargeLimitSocPct
	}
	return 0
}

func (x *ChargingState) GetBatteryPreconditioning() bool {
	if x != nil {
		return x.BatteryPreconditioning
	}
	return false
}

type MotorState struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	Position            MotorState_MotorPosition `protobuf:"varint,1,opt,name=position,proto3,enum=fleet.telemetry.v1.MotorState_MotorPosition" json:"position,omitempty"`
	Rpm                 int32                    `protobuf:"varint,2,opt,name=rpm,proto3" json:"rpm,omitempty"`
	InverterTempCelsius float32                  `protobuf:"fixed32,3,opt,name=inverter_temp_celsius,json=inverterTempCelsius,proto3" json:"inverter_temp_celsius,omitempty"`
	DcBusCurrent        float32                  `protobuf:"fixed32,4,opt,name=dc_bus_current,json=dcBusCurrent,proto3" json:"dc_bus_current,omitempty"`
	DcBusVoltage        float32                  `protobuf:"fixed32,5,opt,name=dc_bus_voltage,json=dcBusVoltage,proto3" json:"dc_bus_voltage,omitempty"`
	MotorTempCelsius    float32                  `protobuf:"fixed32,6,opt,name=motor_temp_celsius,json=motorTempCelsius,proto3" json:"motor_temp_celsius,omitempty"`
	ThrottlePositionPct float32                  `protobuf:"fixed32,7,opt,name=throttle_position_pct,json=throttlePositionPct,proto3" json:"throttle_position_pct,omitempty"`
	TorqueNm            float32                  `protobuf:"fixed32,8,opt,name=torque_nm,json=torqueNm,proto3" json:"torque_nm,omitempty"`
	PowerKw             float32                  `protobuf:"fixed32,9,opt,name=power_kw,json=powerKw,proto3" json:"power_kw,omitempty"`
	Status              MotorState_MotorStatus   `protobuf:"varint,10,opt,name=status,proto3,enum=fleet.telemetry.v1.MotorState_MotorStatus" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MotorState) Reset() {
	*x = MotorState{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorState) ProtoMessage() {}

func (x *MotorState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorState.ProtoReflect.Descriptor instead.
func (*MotorState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *MotorState) GetPosition() MotorState_MotorPosition {
	if x != nil {
		return x.Position
	}
	return MotorState_MOTOR_POSITION_UNSPECIFIED
}

func (x *MotorState) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *MotorState) GetInverterTempCelsius() float32 {
	if x != nil {
		return x.InverterTempCelsius
	}
	return 0
}

func (x *MotorState) GetDcBusCurrent() float32 {
	if x != nil {
		return x.DcBusCurrent
	}
	return 0
}

func (x *MotorState) GetDcBusVoltage() float32 {
	if x != nil {
		return x.DcBusVoltage
	}
	return 0
}

func (x *MotorState) GetMotorTempCelsius() float32 {
	if x != nil {
		return x.MotorTempCelsius
	}
	return 0
}

func (x *MotorState) GetThrottlePositionPct() float32 {
	if x != nil {
		return x.ThrottlePositionPct
	}
	return 0
}

func (x *MotorState) GetTorqueNm() float32 {
	if x != nil {
		return x.TorqueNm
	}
	return 0
}

func (x *MotorState) GetPowerKw() float32 {
	if x != nil {
		return x.PowerKw
	}
	return 0
}

func (x *MotorState) GetStatus() MotorState_MotorStatus {
	if x != nil {
		return x.Status
	}
	return MotorState_MOTOR_STATUS_UNSPECIFIED
}

type TirePressure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontLeftBar  float32                `protobuf:"fixed32,1,opt,name=front_left_bar,json=frontLeftBar,proto3" json:"front_left_bar,omitempty"`
	FrontRightBar float32                `protobuf:"fixed32,2,opt,name=front_right_bar,json=frontRightBar,proto3" json:"front_right_bar,omitempty"`
	RearLeftBar   float32                `protobuf:"fixed32,3,opt,name=rear_left_bar,json=rearLeftBar,proto3" json:"rear_left_bar,omitempty"`
	RearRightBar  float32                `protobuf:"fixed32,4,opt,name=rear_right_bar,json=rearRightBar,proto3" json:"rear_right_bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TirePressure) Reset() {
	*x = TirePressure{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TirePressure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TirePressure) ProtoMessage() {}

func (x *TirePressure) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TirePressure.ProtoReflect.Descriptor instead.
func (*TirePressure) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TirePressure) GetFrontLeftBar() float32 {
	if x != nil {
		return x.FrontLeftBar
	}
	return 0
}

func (x *TirePressure) GetFrontRightBar() float32 {
	if x != nil {
		return x.FrontRightBar
	}
	return 0
}

func (x *TirePressure) GetRearLeftBar() float32 {
	if x != nil {
		return x.RearLeftBar
	}
	return 0
}

func (x *TirePressure) GetRearRightBar() float32 {
	if x != nil {
		return x.RearRightBar
	}
	return 0
}

type CabinState struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	InsideTempCelsius       float32                `protobuf:"fixed32,1,opt,name=inside_temp_celsius,json=insideTempCelsius,proto3" json:"inside_temp_celsius,omitempty"`
	OutsideTempCelsius      float32                `protobuf:"fixed32,2,opt,name=outside_temp_celsius,json=outsideTempCelsius,proto3" json:"outside_temp_celsius,omitempty"`
	ClimateOn               bool                   `protobuf:"varint,3,opt,name=climate_on,json=climateOn,proto3" json:"climate_on,omitempty"`
	IsLocked                bool                   `protobuf:"varint,4,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	SentryOrGuardModeActive bool                   `protobuf:"varint,5,opt,name=sentry_or_guard_mode_active,json=sentryOrGuardModeActive,proto3" json:"sentry_or_guard_mode_active,omitempty"` // Camera security (Tesla Sentry / Rivian Gear Guard)
	// Passenger closures (Sedans, SUVs, Trucks)
	DriverDoorOpen      bool `protobuf:"varint,6,opt,name=driver_door_open,json=driverDoorOpen,proto3" json:"driver_door_open,omitempty"`
	PassengerDoorOpen   bool `protobuf:"varint,7,opt,name=passenger_door_open,json=passengerDoorOpen,proto3" json:"passenger_door_open,omitempty"`
	RearLeftDoorOpen    bool `protobuf:"varint,8,opt,name=rear_left_door_open,json=rearLeftDoorOpen,proto3" json:"rear_left_door_open,omitempty"`
	RearRightDoorOpen   bool `protobuf:"varint,9,opt,name=rear_right_door_open,json=rearRightDoorOpen,proto3" json:"rear_right_door_open,omitempty"`
	FrunkOpen           bool `protobuf:"varint,10,opt,name=frunk_open,json=frunkOpen,proto3" json:"frunk_open,omitempty"`
	TrunkOrLiftgateOpen bool `protobuf:"varint,11,opt,name=trunk_or_liftgate_open,json=trunkOrLiftgateOpen,proto3" json:"trunk_or_liftgate_open,omitempty"` // Passenger car trunk or SUV rear liftgate
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CabinState) Reset() {
	*x = CabinState{}
	mi := &file_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CabinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinState) ProtoMessage() {}

func (x *CabinState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinState.ProtoReflect.Descriptor instead.
func (*CabinState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *CabinState) GetInsideTempCelsius() float32 {
	if x != nil {
		return x.InsideTempCelsius
	}
	return 0
}

func (x *CabinState) GetOutsideTempCelsius() float32 {
	if x != nil {
		return x.OutsideTempCelsius
	}
	return 0
}

func (x *CabinState) GetClimateOn() bool {
	if x != nil {
		return x.ClimateOn
	}
	return false
}

func (x *CabinState) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *CabinState) GetSentryOrGuardModeActive() bool {
	if x != nil {
		return x.SentryOrGuardModeActive
	}
	return false
}

func (x *CabinState) GetDriverDoorOpen() bool {
	if x != nil {
		return x.DriverDoorOpen
	}
	return false
}

func (x *CabinState) GetPassengerDoorOpen() bool {
	if x != nil {
		return x.PassengerDoorOpen
	}
	return false
}

func (x *CabinState) GetRearLeftDoorOpen() bool {
	if x != nil {
		return x.RearLeftDoorOpen
	}
	return false
}

func (x *CabinState) GetRearRightDoorOpen() bool {
	if x != nil {
		return x.RearRightDoorOpen
	}
	return false
}

func (x *CabinState) GetFrunkOpen() bool {
	if x != nil {
		return x.FrunkOpen
	}
	return false
}

func (x *CabinState) GetTrunkOrLiftgateOpen() bool {
	if x != nil {
		return x.TrunkOrLiftgateOpen
	}
	return false
}

// Active/Air Suspension & Inclinometer (Rivian R1T, Cybertruck, Model S/X, etc.)
type SuspensionState struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	RideHeight        SuspensionState_RideHeight `protobuf:"varint,1,opt,name=ride_height,json=rideHeight,proto3,enum=fleet.telemetry.v1.SuspensionState_RideHeight" json:"ride_height,omitempty"`
	GroundClearanceMm float32                    `protobuf:"fixed32,2,opt,name=ground_clearance_mm,json=groundClearanceMm,proto3" json:"ground_clearance_mm,omitempty"`
	PitchDegrees      float32                    `protobuf:"fixed32,3,opt,name=pitch_degrees,json=pitchDegrees,proto3" json:"pitch_degrees,omitempty"` // Inclinometer: front/rear pitch (camp mode auto-leveling & off-roading)
	RollDegrees       float32                    `protobuf:"fixed32,4,opt,name=roll_degrees,json=rollDegrees,proto3" json:"roll_degrees,omitempty"`    // Inclinometer: side-to-side roll
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuspensionState) Reset() {
	*x = SuspensionState{}
	mi := &file_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspensionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspensionState) ProtoMessage() {}

func (x *SuspensionState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspensionState.ProtoReflect.Descriptor instead.
func (*SuspensionState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *SuspensionState) GetRideHeight() SuspensionState_RideHeight {
	if x != nil {
		return x.RideHeight
	}
	return SuspensionState_RIDE_HEIGHT_UNSPECIFIED
}

func (x *SuspensionState) GetGroundClearanceMm() float32 {
	if x != nil {
		return x.GroundClearanceMm
	}
	return 0
}

func (x *SuspensionState) GetPitchDegrees() float32 {
	if x != nil {
		return x.PitchDegrees
	}
	return 0
}

func (x *SuspensionState) GetRollDegrees() float32 {
	if x != nil {
		return x.RollDegrees
	}
	return 0
}

// ============================================================================
// TRUCK-SPECIFIC TELEMETRY
// Explicitly populated for electric pickup trucks (Rivian R1T, Ford F-150
// Lightning, Tesla Cybertruck, Silverado EV). Omitted/nil for sedans/SUVs.
// ============================================================================
type TruckState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Truck Bed & Tailgate Closures ---
	TailgateOpen        bool  `protobuf:"varint,1,opt,name=tailgate_open,json=tailgateOpen,proto3" json:"tailgate_open,omitempty"`
	TonneauCoverPctOpen int32 `protobuf:"varint,2,opt,name=tonneau_cover_pct_open,json=tonneauCoverPctOpen,proto3" json:"tonneau_cover_pct_open,omitempty"` // 0 = fully closed, 100 = fully open
	GearTunnelLeftOpen  bool  `protobuf:"varint,3,opt,name=gear_tunnel_left_open,json=gearTunnelLeftOpen,proto3" json:"gear_tunnel_left_open,omitempty"`    // [Rivian R1T specific]
	GearTunnelRightOpen bool  `protobuf:"varint,4,opt,name=gear_tunnel_right_open,json=gearTunnelRightOpen,proto3" json:"gear_tunnel_right_open,omitempty"` // [Rivian R1T specific]
	// --- Towing & Trailer Subsystem ---
	TrailerConnected         bool    `protobuf:"varint,5,opt,name=trailer_connected,json=trailerConnected,proto3" json:"trailer_connected,omitempty"`                              // Detected via 7-pin trailer connector
	EstimatedTrailerWeightKg float32 `protobuf:"fixed32,6,opt,name=estimated_trailer_weight_kg,json=estimatedTrailerWeightKg,proto3" json:"estimated_trailer_weight_kg,omitempty"` // Auto-calculated from motor torque vs acceleration
	TrailerBrakeGain         float32 `protobuf:"fixed32,7,opt,name=trailer_brake_gain,json=trailerBrakeGain,proto3" json:"trailer_brake_gain,omitempty"`                           // Integrated trailer brake controller gain (0.0 - 10.0)
	TowModeActive            bool    `protobuf:"varint,8,opt,name=tow_mode_active,json=towModeActive,proto3" json:"tow_mode_active,omitempty"`
	// --- Work & Exportable Power (Vehicle-to-Load / V2L) ---
	BedOutletsActive  bool    `protobuf:"varint,9,opt,name=bed_outlets_active,json=bedOutletsActive,proto3" json:"bed_outlets_active,omitempty"`        // 120V / 240V AC power outlets in the bed
	BedOutletsPowerKw float32 `protobuf:"fixed32,10,opt,name=bed_outlets_power_kw,json=bedOutletsPowerKw,proto3" json:"bed_outlets_power_kw,omitempty"` // Instantaneous power draw from bed outlets
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TruckState) Reset() {
	*x = TruckState{}
	mi := &file_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruckState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckState) ProtoMessage() {}

func (x *TruckState) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckState.ProtoReflect.Descriptor instead.
func (*TruckState) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *TruckState) GetTailgateOpen() bool {
	if x != nil {
		return x.TailgateOpen
	}
	return false
}

func (x *TruckState) GetTonneauCoverPctOpen() int32 {
	if x != nil {
		return x.TonneauCoverPctOpen
	}
	return 0
}

func (x *TruckState) GetGearTunnelLeftOpen() bool {
	if x != nil {
		return x.GearTunnelLeftOpen
	}
	return false
}

func (x *TruckState) GetGearTunnelRightOpen() bool {
	if x != nil {
		return x.GearTunnelRightOpen
	}
	return false
}

func (x *TruckState) GetTrailerConnected() bool {
	if x != nil {
		return x.TrailerConnected
	}
	return false
}

func (x *TruckState) GetEstimatedTrailerWeightKg() float32 {
	if x != nil {
		return x.EstimatedTrailerWeightKg
	}
	return 0
}

func (x *TruckState) GetTrailerBrakeGain() float32 {
	if x != nil {
		return x.TrailerBrakeGain
	}
	return 0
}

func (x *TruckState) GetTowModeActive() bool {
	if x != nil {
		return x.TowModeActive
	}
	return false
}

func (x *TruckState) GetBedOutletsActive() bool {
	if x != nil {
		return x.BedOutletsActive
	}
	return false
}

func (x *TruckState) GetBedOutletsPowerKw() float32 {
	if x != nil {
		return x.BedOutletsPowerKw
	}
	return 0
}

type VehicleTelemetry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Vin         string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Location    *GPSLocation           `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Model       VehicleModel           `protobuf:"varint,4,opt,name=model,proto3,enum=fleet.telemetry.v1.VehicleModel" json:"model,omitempty"`
	// Dynamics & Driver Controls
	Gear             Gear    `protobuf:"varint,5,opt,name=gear,proto3,enum=fleet.telemetry.v1.Gear" json:"gear,omitempty"`
	SpeedKmh         float32 `protobuf:"fixed32,6,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	BrakePedalPct    float32 `protobuf:"fixed32,7,opt,name=brake_pedal_pct,json=brakePedalPct,proto3" json:"brake_pedal_pct,omitempty"`
	OdometerKm       float32 `protobuf:"fixed32,8,opt,name=odometer_km,json=odometerKm,proto3" json:"odometer_km,omitempty"`
	RemainingRangeKm float32 `protobuf:"fixed32,9,opt,name=remaining_range_km,json=remainingRangeKm,proto3" json:"remaining_range_km,omitempty"`
	VehicleMode      string  `protobuf:"bytes,10,opt,name=vehicle_mode,json=vehicleMode,proto3" json:"vehicle_mode,omitempty"` // e.g., "Standard", "Chill", "All-Terrain", "Conserve", "Tow"
	// Common EV Subsystems (All vehicles: Sedan, SUV, Truck, Van)
	BatteryState  *BatteryState  `protobuf:"bytes,11,opt,name=battery_state,json=batteryState,proto3" json:"battery_state,omitempty"`
	ChargingState *ChargingState `protobuf:"bytes,12,opt,name=charging_state,json=chargingState,proto3" json:"charging_state,omitempty"`
	MotorStates   []*MotorState  `protobuf:"bytes,13,rep,name=motor_states,json=motorStates,proto3" json:"motor_states,omitempty"` // 1 (RWD), 2 (Dual-Motor AWD), or 4 (Quad-Motor)
	TirePressure  *TirePressure  `protobuf:"bytes,14,opt,name=tire_pressure,json=tirePressure,proto3" json:"tire_pressure,omitempty"`
	CabinState    *CabinState    `protobuf:"bytes,15,opt,name=cabin_state,json=cabinState,proto3" json:"cabin_state,omitempty"`
	// Optional: Active/Air Suspension (Trucks, SUVs, and high-end EVs)
	SuspensionState *SuspensionState `protobuf:"bytes,16,opt,name=suspension_state,json=suspensionState,proto3" json:"suspension_state,omitempty"`
	// Explicit Truck-Specific Subsystem (Rivian R1T, F-150 Lightning, Cybertruck)
	// Left unset/nil for passenger sedans like Tesla Model 3.
	TruckState *TruckState `protobuf:"bytes,17,opt,name=truck_state,json=truckState,proto3" json:"truck_state,omitempty"`
	// Active Diagnostic Trouble Codes / Alerts
	ActiveAlertCodes []string `protobuf:"bytes,18,rep,name=active_alert_codes,json=activeAlertCodes,proto3" json:"active_alert_codes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleTelemetry) Reset() {
	*x = VehicleTelemetry{}
	mi := &file_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleTelemetry) ProtoMessage() {}

func (x *VehicleTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleTelemetry.ProtoReflect.Descriptor instead.
func (*VehicleTelemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *VehicleTelemetry) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleTelemetry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VehicleTelemetry) GetLocation() *GPSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *VehicleTelemetry) GetModel() VehicleModel {
	if x != nil {
		return x.Model
	}
	return VehicleModel_VEHICLE_MODEL_UNSPECIFIED
}

func (x *VehicleTelemetry) GetGear() Gear {
	if x != nil {
		return x.Gear
	}
	return Gear_GEAR_UNSPECIFIED
}

func (x *VehicleTelemetry) GetSpeedKmh() float32 {
	if x != nil {
		return x.SpeedKmh
	}
	return 0
}

func (x *VehicleTelemetry) GetBrakePedalPct() float32 {
	if x != nil {
		return x.BrakePedalPct
	}
	return 0
}

func (x *VehicleTelemetry) GetOdometerKm() float32 {
	if x != nil {
		return x.OdometerKm
	}
	return 0
}

func (x *VehicleTelemetry) GetRemainingRangeKm() float32 {
	if x != nil {
		return x.RemainingRangeKm
	}
	return 0
}

func (x *VehicleTelemetry) GetVehicleMode() string {
	if x != nil {
		return x.VehicleMode
	}
	return ""
}

func (x *VehicleTelemetry) GetBatteryState() *BatteryState {
	if x != nil {
		return x.BatteryState
	}
	return nil
}

func (x *VehicleTelemetry) GetChargingState() *ChargingState {
	if x != nil {
		return x.ChargingState
	}
	return nil
}

func (x *VehicleTelemetry) GetMotorStates() []*MotorState {
	if x != nil {
		return x.MotorStates
	}
	return nil
}

func (x *VehicleTelemetry) GetTirePressure() *TirePressure {
	if x != nil {
		return x.TirePressure
	}
	return nil
}

func (x *VehicleTelemetry) GetCabinState() *CabinState {
	if x != nil {
		return x.CabinState
	}
	return nil
}

func (x *VehicleTelemetry) GetSuspensionState() *SuspensionState {
	if x != nil {
		return x.SuspensionState
	}
	return nil
}

func (x *VehicleTelemetry) GetTruckState() *TruckState {
	if x != nil {
		return x.TruckState
	}
	return nil
}

func (x *VehicleTelemetry) GetActiveAlertCodes() []string {
	if x != nil {
		return x.ActiveAlertCodes
	}
	return nil
}

type VehicleAlert struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Vin           string                  `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	TimestampMs   int64                   `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Location      *GPSLocation            `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Level         VehicleAlert_AlertLevel `protobuf:"varint,4,opt,name=level,proto3,enum=fleet.telemetry.v1.VehicleAlert_AlertLevel" json:"level,omitempty"`
	Code          string                  `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                  `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Metadata      map[string]string       `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleAlert) Reset() {
	*x = VehicleAlert{}
	mi := &file_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleAlert) ProtoMessage() {}

func (x *VehicleAlert) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleAlert.ProtoReflect.Descriptor instead.
func (*VehicleAlert) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *VehicleAlert) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *VehicleAlert) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *VehicleAlert) GetLocation() *GPSLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *VehicleAlert) GetLevel() VehicleAlert_AlertLevel {
	if x != nil {
		return x.Level
	}
	return VehicleAlert_ALERT_LEVEL_UNSPECIFIED
}

func (x *VehicleAlert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VehicleAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VehicleAlert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x12fleet.telemetry.v1\"\xe8\x01\n" +
	"\vGPSLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x01R\aheading\x12\x12\n" +
	"\x04pdop\x18\x06 \x01(\x01R\x04pdop\x12\x12\n" +
	"\x04hdop\x18\a \x01(\x01R\x04hdop\x12+\n" +
	"\x11location_provider\x18\b \x01(\tR\x10locationProvider\"\xd0\x06\n" +
	"\fBatteryState\x12!\n" +
	"\fcell_voltage\x18\x01 \x03(\x02R\vcellVoltage\x12&\n" +
	"\x0fstate_of_charge\x18\x02 \x01(\x02R\rstateOfCharge\x12!\n" +
	"\fpack_voltage\x18\x03 \x01(\x02R\vpackVoltage\x12!\n" +
	"\fpack_current\x18\x04 \x01(\x02R\vpackCurrent\x120\n" +
	"\x14max_cell_temperature\x18\x05 \x01(\x02R\x12maxCellTemperature\x120\n" +
	"\x14min_cell_temperature\x18\x06 \x01(\x02R\x12minCellTemperature\x12)\n" +
	"\x10pack_temperature\x18\a \x01(\x02R\x0fpackTemperature\x12\x1d\n" +
	"\n" +
	"pack_power\x18\b \x01(\x02R\tpackPower\x12\x1f\n" +
	"\vpack_health\x18\t \x01(\x02R\n" +
	"packHealth\x126\n" +
	"\x17pack_remaining_capacity\x18\n" +
	" \x01(\x02R\x15packRemainingCapacity\x12(\n" +
	"\x10pack_cycle_count\x18\v \x01(\x05R\x0epackCycleCount\x12O\n" +
	"\vpack_status\x18\f \x01(\x0e2..fleet.telemetry.v1.BatteryState.BatteryStatusR\n" +
	"packStatus\x12(\n" +
	"\x10min_cell_voltage\x18\r \x01(\x02R\x0eminCellVoltage\x12(\n" +
	"\x10max_cell_voltage\x18\x0e \x01(\x02R\x0emaxCellVoltage\x129\n" +
	"\x19low_voltage_battery_volts\x18\x0f \x01(\x02R\x16lowVoltageBatteryVolts\"\x9d\x01\n" +
	"\rBatteryStatus\x12\x1e\n" +
	"\x1aBATTERY_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BATTERY_STATUS_OK\x10\x01\x12\x1b\n" +
	"\x17BATTERY_STATUS_CHARGING\x10\x02\x12\x1e\n" +
	"\x1aBATTERY_STATUS_DISCHARGING\x10\x03\x12\x18\n" +
	"\x14BATTERY_STATUS_FAULT\x10\x04\"\xda\b\n" +
	"\rChargingState\x12C\n" +
	"\x05state\x18\x01 \x01(\x0e2-.fleet.telemetry.v1.ChargingState.ChargeStateR\x05state\x12P\n" +
	"\fcharger_type\x18\x02 \x01(\x0e2-.fleet.telemetry.v1.ChargingState.ChargerTypeR\vchargerType\x121\n" +
	"\x15charge_port_door_open\x18\x03 \x01(\bR\x12chargePortDoorOpen\x129\n" +
	"\x19charge_port_latch_engaged\x18\x04 \x01(\bR\x16chargePortLatchEngaged\x12'\n" +
	"\x0fcharger_voltage\x18\x05 \x01(\x02R\x0echargerVoltage\x124\n" +
	"\x16charger_actual_current\x18\x06 \x01(\x02R\x14chargerActualCurrent\x122\n" +
	"\x15charger_pilot_current\x18\a \x01(\x02R\x13chargerPilotCurrent\x12%\n" +
	"\x0echarger_phases\x18\b \x01(\x05R\rchargerPhases\x12*\n" +
	"\x11charging_power_kw\x18\t \x01(\x02R\x0fchargingPowerKw\x127\n" +
	"\x18session_energy_added_kwh\x18\n" +
	" \x01(\x02R\x15sessionEnergyAddedKwh\x124\n" +
	"\x17charge_rate_km_per_hour\x18\v \x01(\x02R\x13chargeRateKmPerHour\x123\n" +
	"\x16minutes_to_full_charge\x18\f \x01(\x05R\x13minutesToFullCharge\x12/\n" +
	"\x14charge_limit_soc_pct\x18\r \x01(\x05R\x11chargeLimitSocPct\x127\n" +
	"\x17battery_preconditioning\x18\x0e \x01(\bR\x16batteryPreconditioning\"\xce\x01\n" +
	"\vChargeState\x12\x1c\n" +
	"\x18CHARGE_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHARGE_STATE_DISCONNECTED\x10\x01\x12\x1a\n" +
	"\x16CHARGE_STATE_CONNECTED\x10\x02\x12\x19\n" +
	"\x15CHARGE_STATE_CHARGING\x10\x03\x12\x19\n" +
	"\x15CHARGE_STATE_COMPLETE\x10\x04\x12\x18\n" +
	"\x14CHARGE_STATE_STOPPED\x10\x05\x12\x16\n" +
	"\x12CHARGE_STATE_FAULT\x10\x06\"\x7f\n" +
	"\vChargerType\x12\x1c\n" +
	"\x18CHARGER_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CHARGER_TYPE_AC_LEVEL_1\x10\x01\x12\x1b\n" +
	"\x17CHARGER_TYPE_AC_LEVEL_2\x10\x02\x12\x18\n" +
	"\x14CHARGER_TYPE_DC_FAST\x10\x03\"\xb0\x06\n" +
	"\n" +
	"MotorState\x12H\n" +
	"\bposition\x18\x01 \x01(\x0e2,.fleet.telemetry.v1.MotorState.MotorPositionR\bposition\x12\x10\n" +
	"\x03rpm\x18\x02 \x01(\x05R\x03rpm\x122\n" +
	"\x15inverter_temp_celsius\x18\x03 \x01(\x02R\x13inverterTempCelsius\x12$\n" +
	"\x0edc_bus_current\x18\x04 \x01(\x02R\fdcBusCurrent\x12$\n" +
	"\x0edc_bus_voltage\x18\x05 \x01(\x02R\fdcBusVoltage\x12,\n" +
	"\x12motor_temp_celsius\x18\x06 \x01(\x02R\x10motorTempCelsius\x122\n" +
	"\x15throttle_position_pct\x18\a \x01(\x02R\x13throttlePositionPct\x12\x1b\n" +
	"\ttorque_nm\x18\b \x01(\x02R\btorqueNm\x12\x19\n" +
	"\bpower_kw\x18\t \x01(\x02R\apowerKw\x12B\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2*.fleet.telemetry.v1.MotorState.MotorStatusR\x06status\"\xde\x01\n" +
	"\rMotorPosition\x12\x1e\n" +
	"\x1aMOTOR_POSITION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MOTOR_POSITION_FRONT\x10\x01\x12\x17\n" +
	"\x13MOTOR_POSITION_REAR\x10\x02\x12\x1d\n" +
	"\x19MOTOR_POSITION_FRONT_LEFT\x10\x03\x12\x1e\n" +
	"\x1aMOTOR_POSITION_FRONT_RIGHT\x10\x04\x12\x1c\n" +
	"\x18MOTOR_POSITION_REAR_LEFT\x10\x05\x12\x1d\n" +
	"\x19MOTOR_POSITION_REAR_RIGHT\x10\x06\"\x86\x01\n" +
	"\vMotorStatus\x12\x1c\n" +
	"\x18MOTOR_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bMOTOR_STATUS_READY_TO_DRIVE\x10\x01\x12 \n" +
	"\x1cMOTOR_STATUS_READY_TO_CHARGE\x10\x02\x12\x16\n" +
	"\x12MOTOR_STATUS_FAULT\x10\x03\"\xa6\x01\n" +
	"\fTirePressure\x12$\n" +
	"\x0efront_left_bar\x18\x01 \x01(\x02R\ffrontLeftBar\x12&\n" +
	"\x0ffront_right_bar\x18\x02 \x01(\x02R\rfrontRightBar\x12\"\n" +
	"\rrear_left_bar\x18\x03 \x01(\x02R\vrearLeftBar\x12$\n" +
	"\x0erear_right_bar\x18\x04 \x01(\x02R\frearRightBar\"\xf6\x03\n" +
	"\n" +
	"CabinState\x12.\n" +
	"\x13inside_temp_celsius\x18\x01 \x01(\x02R\x11insideTempCelsius\x120\n" +
	"\x14outside_temp_celsius\x18\x02 \x01(\x02R\x12outsideTempCelsius\x12\x1d\n" +
	"\n" +
	"climate_on\x18\x03 \x01(\bR\tclimateOn\x12\x1b\n" +
	"\tis_locked\x18\x04 \x01(\bR\bisLocked\x12<\n" +
	"\x1bsentry_or_guard_mode_active\x18\x05 \x01(\bR\x17sentryOrGuardModeActive\x12(\n" +
	"\x10driver_door_open\x18\x06 \x01(\bR\x0edriverDoorOpen\x12.\n" +
	"\x13passenger_door_open\x18\a \x01(\bR\x11passengerDoorOpen\x12-\n" +
	"\x13rear_left_door_open\x18\b \x01(\bR\x10rearLeftDoorOpen\x12/\n" +
	"\x14rear_right_door_open\x18\t \x01(\bR\x11rearRightDoorOpen\x12\x1d\n" +
	"\n" +
	"frunk_open\x18\n" +
	" \x01(\bR\tfrunkOpen\x123\n" +
	"\x16trunk_or_liftgate_open\x18\v \x01(\bR\x13trunkOrLiftgateOpen\"\x80\x03\n" +
	"\x0fSuspensionState\x12O\n" +
	"\vride_height\x18\x01 \x01(\x0e2..fleet.telemetry.v1.SuspensionState.RideHeightR\n" +
	"rideHeight\x12.\n" +
	"\x13ground_clearance_mm\x18\x02 \x01(\x02R\x11groundClearanceMm\x12#\n" +
	"\rpitch_degrees\x18\x03 \x01(\x02R\fpitchDegrees\x12!\n" +
	"\froll_degrees\x18\x04 \x01(\x02R\vrollDegrees\"\xa3\x01\n" +
	"\n" +
	"RideHeight\x12\x1b\n" +
	"\x17RIDE_HEIGHT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RIDE_HEIGHT_VERY_LOW\x10\x01\x12\x13\n" +
	"\x0fRIDE_HEIGHT_LOW\x10\x02\x12\x18\n" +
	"\x14RIDE_HEIGHT_STANDARD\x10\x03\x12\x14\n" +
	"\x10RIDE_HEIGHT_HIGH\x10\x04\x12\x19\n" +
	"\x15RIDE_HEIGHT_VERY_HIGH\x10\x05\"\xef\x03\n" +
	"\n" +
	"TruckState\x12#\n" +
	"\rtailgate_open\x18\x01 \x01(\bR\ftailgateOpen\x123\n" +
	"\x16tonneau_cover_pct_open\x18\x02 \x01(\x05R\x13tonneauCoverPctOpen\x121\n" +
	"\x15gear_tunnel_left_open\x18\x03 \x01(\bR\x12gearTunnelLeftOpen\x123\n" +
	"\x16gear_tunnel_right_open\x18\x04 \x01(\bR\x13gearTunnelRightOpen\x12+\n" +
	"\x11trailer_connected\x18\x05 \x01(\bR\x10trailerConnected\x12=\n" +
	"\x1bestimated_trailer_weight_kg\x18\x06 \x01(\x02R\x18estimatedTrailerWeightKg\x12,\n" +
	"\x12trailer_brake_gain\x18\a \x01(\x02R\x10trailerBrakeGain\x12&\n" +
	"\x0ftow_mode_active\x18\b \x01(\bR\rtowModeActive\x12,\n" +
	"\x12bed_outlets_active\x18\t \x01(\bR\x10bedOutletsActive\x12/\n" +
	"\x14bed_outlets_power_kw\x18\n" +
	" \x01(\x02R\x11bedOutletsPowerKw\"\xbc\a\n" +
	"\x10VehicleTelemetry\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12;\n" +
	"\blocation\x18\x03 \x01(\v2\x1f.fleet.telemetry.v1.GPSLocationR\blocation\x126\n" +
	"\x05model\x18\x04 \x01(\x0e2 .fleet.telemetry.v1.VehicleModelR\x05model\x12,\n" +
	"\x04gear\x18\x05 \x01(\x0e2\x18.fleet.telemetry.v1.GearR\x04gear\x12\x1b\n" +
	"\tspeed_kmh\x18\x06 \x01(\x02R\bspeedKmh\x12&\n" +
	"\x0fbrake_pedal_pct\x18\a \x01(\x02R\rbrakePedalPct\x12\x1f\n" +
	"\vodometer_km\x18\b \x01(\x02R\n" +
	"odometerKm\x12,\n" +
	"\x12remaining_range_km\x18\t \x01(\x02R\x10remainingRangeKm\x12!\n" +
	"\fvehicle_mode\x18\n" +
	" \x01(\tR\vvehicleMode\x12E\n" +
	"\rbattery_state\x18\v \x01(\v2 .fleet.telemetry.v1.BatteryStateR\fbatteryState\x12H\n" +
	"\x0echarging_state\x18\f \x01(\v2!.fleet.telemetry.v1.ChargingStateR\rchargingState\x12A\n" +
	"\fmotor_states\x18\r \x03(\v2\x1e.fleet.telemetry.v1.MotorStateR\vmotorStates\x12E\n" +
	"\rtire_pressure\x18\x0e \x01(\v2 .fleet.telemetry.v1.TirePressureR\ftirePressure\x12?\n" +
	"\vcabin_state\x18\x0f \x01(\v2\x1e.fleet.telemetry.v1.CabinStateR\n" +
	"cabinState\x12N\n" +
	"\x10suspension_state\x18\x10 \x01(\v2#.fleet.telemetry.v1.SuspensionStateR\x0fsuspensionState\x12?\n" +
	"\vtruck_state\x18\x11 \x01(\v2\x1e.fleet.telemetry.v1.TruckStateR\n" +
	"truckState\x12,\n" +
	"\x12active_alert_codes\x18\x12 \x03(\tR\x10activeAlertCodes\"\x8e\x04\n" +
	"\fVehicleAlert\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12;\n" +
	"\blocation\x18\x03 \x01(\v2\x1f.fleet.telemetry.v1.GPSLocationR\blocation\x12A\n" +
	"\x05level\x18\x04 \x01(\x0e2+.fleet.telemetry.v1.VehicleAlert.AlertLevelR\x05level\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12J\n" +
	"\bmetadata\x18\a \x03(\v2..fleet.telemetry.v1.VehicleAlert.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\n" +
	"AlertLevel\x12\x1b\n" +
	"\x17ALERT_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ALERT_LEVEL_INFO\x10\x01\x12\x17\n" +
	"\x13ALERT_LEVEL_WARNING\x10\x02\x12\x15\n" +
	"\x11ALERT_LEVEL_ERROR\x10\x03\x12\x18\n" +
	"\x14ALERT_LEVEL_CRITICAL\x10\x04*_\n" +
	"\x04Gear\x12\x14\n" +
	"\x10GEAR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tGEAR_PARK\x10\x01\x12\x10\n" +
	"\fGEAR_REVERSE\x10\x02\x12\x10\n" +
	"\fGEAR_NEUTRAL\x10\x03\x12\x0e\n" +
	"\n" +
	"GEAR_DRIVE\x10\x04*\xcd\x02\n" +
	"\fVehicleModel\x12\x1d\n" +
	"\x19VEHICLE_MODEL_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVEHICLE_MODEL_TESLA_MODEL_3\x10\x01\x12\x1f\n" +
	"\x1bVEHICLE_MODEL_TESLA_MODEL_Y\x10\x02\x12\x1f\n" +
	"\x1bVEHICLE_MODEL_TESLA_MODEL_S\x10\x03\x12\x1f\n" +
	"\x1bVEHICLE_MODEL_TESLA_MODEL_X\x10\x04\x12\"\n" +
	"\x1eVEHICLE_MODEL_TESLA_CYBERTRUCK\x10\x05\x12\x1c\n" +
	"\x18VEHICLE_MODEL_TESLA_SEMI\x10\x06\x12\x1c\n" +
	"\x18VEHICLE_MODEL_RIVIAN_R1T\x10\a\x12\x1c\n" +
	"\x18VEHICLE_MODEL_RIVIAN_R1S\x10\b\x12\x1c\n" +
	"\x18VEHICLE_MODEL_RIVIAN_EDV\x10\tB>Z<github.com/itsnairr/fleet-telemetry-engine/internal/protocolb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_telemetry_proto_goTypes = []any{
	(Gear)(0),                       // 0: fleet.telemetry.v1.Gear
	(VehicleModel)(0),               // 1: fleet.telemetry.v1.VehicleModel
	(BatteryState_BatteryStatus)(0), // 2: fleet.telemetry.v1.BatteryState.BatteryStatus
	(ChargingState_ChargeState)(0),  // 3: fleet.telemetry.v1.ChargingState.ChargeState
	(ChargingState_ChargerType)(0),  // 4: fleet.telemetry.v1.ChargingState.ChargerType
	(MotorState_MotorPosition)(0),   // 5: fleet.telemetry.v1.MotorState.MotorPosition
	(MotorState_MotorStatus)(0),     // 6: fleet.telemetry.v1.MotorState.MotorStatus
	(SuspensionState_RideHeight)(0), // 7: fleet.telemetry.v1.SuspensionState.RideHeight
	(VehicleAlert_AlertLevel)(0),    // 8: fleet.telemetry.v1.VehicleAlert.AlertLevel
	(*GPSLocation)(nil),             // 9: fleet.telemetry.v1.GPSLocation
	(*BatteryState)(nil),            // 10: fleet.telemetry.v1.BatteryState
	(*ChargingState)(nil),           // 11: fleet.telemetry.v1.ChargingState
	(*MotorState)(nil),              // 12: fleet.telemetry.v1.MotorState
	(*TirePressure)(nil),            // 13: fleet.telemetry.v1.TirePressure
	(*CabinState)(nil),              // 14: fleet.telemetry.v1.CabinState
	(*SuspensionState)(nil),         // 15: fleet.telemetry.v1.SuspensionState
	(*TruckState)(nil),              // 16: fleet.telemetry.v1.TruckState
	(*VehicleTelemetry)(nil),        // 17: fleet.telemetry.v1.VehicleTelemetry
	(*VehicleAlert)(nil),            // 18: fleet.telemetry.v1.VehicleAlert
	nil,                             // 19: fleet.telemetry.v1.VehicleAlert.MetadataEntry
}
var file_telemetry_proto_depIdxs = []int32{
	2,  // 0: fleet.telemetry.v1.BatteryState.pack_status:type_name -> fleet.telemetry.v1.BatteryState.BatteryStatus
	3,  // 1: fleet.telemetry.v1.ChargingState.state:type_name -> fleet.telemetry.v1.ChargingState.ChargeState
	4,  // 2: fleet.telemetry.v1.ChargingState.charger_type:type_name -> fleet.telemetry.v1.ChargingState.ChargerType
	5,  // 3: fleet.telemetry.v1.MotorState.position:type_name -> fleet.telemetry.v1.MotorState.MotorPosition
	6,  // 4: fleet.telemetry.v1.MotorState.status:type_name -> fleet.telemetry.v1.MotorState.MotorStatus
	7,  // 5: fleet.telemetry.v1.SuspensionState.ride_height:type_name -> fleet.telemetry.v1.SuspensionState.RideHeight
	9,  // 6: fleet.telemetry.v1.VehicleTelemetry.location:type_name -> fleet.telemetry.v1.GPSLocation
	1,  // 7: fleet.telemetry.v1.VehicleTelemetry.model:type_name -> fleet.telemetry.v1.VehicleModel
	0,  // 8: fleet.telemetry.v1.VehicleTelemetry.gear:type_name -> fleet.telemetry.v1.Gear
	10, // 9: fleet.telemetry.v1.VehicleTelemetry.battery_state:type_name -> fleet.telemetry.v1.BatteryState
	11, // 10: fleet.telemetry.v1.VehicleTelemetry.charging_state:type_name -> fleet.telemetry.v1.ChargingState
	12, // 11: fleet.telemetry.v1.VehicleTelemetry.motor_states:type_name -> fleet.telemetry.v1.MotorState
	13, // 12: fleet.telemetry.v1.VehicleTelemetry.tire_pressure:type_name -> fleet.telemetry.v1.TirePressure
	14, // 13: fleet.telemetry.v1.VehicleTelemetry.cabin_state:type_name -> fleet.telemetry.v1.CabinState
	15, // 14: fleet.telemetry.v1.VehicleTelemetry.suspension_state:type_name -> fleet.telemetry.v1.SuspensionState
	16, // 15: fleet.telemetry.v1.VehicleTelemetry.truck_state:type_name -> fleet.telemetry.v1.TruckState
	9,  // 16: fleet.telemetry.v1.VehicleAlert.location:type_name -> fleet.telemetry.v1.GPSLocation
	8,  // 17: fleet.telemetry.v1.VehicleAlert.level:type_name -> fleet.telemetry.v1.VehicleAlert.AlertLevel
	19, // 18: fleet.telemetry.v1.VehicleAlert.metadata:type_name -> fleet.telemetry.v1.VehicleAlert.MetadataEntry
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
